#!/usr/bin/env bash
unset STACK_YAML
(
    cd ~/.config/nixpkgs/apps/xmonad
    stack build --copy-bins --local-bin-path ~/.xmonad/
    mv ~/.xmonad/xmonad-config-exe ~/.xmonad/xmonad-x86_64-linux
) 2>&1 | tee ~/.cache/xmonad/build.out
