{
  "creation_rules": [
    {
      "key_groups": [
        {
          "age": [
            "age12zlz6lvcdk6eqaewfylg35w0syh58sm7gh53q5vvn7hd7c6nngyseftjxl"
          ]
        }
      ],
      "path_regex": "hosts/hexagon/secrets.yaml$"
    },
    {
      "key_groups": [
        {
          "age": [
            "age16ldycczfl4ne520ar8kx56t00u55s8gq69dy0q72hh77jl3qgu7ql9a8wc"
          ]
        }
      ],
      "path_regex": "hosts/hexgoer/secrets.yaml$"
    },
    {
      "key_groups": [
        {
          "age": [
            "age12zlz6lvcdk6eqaewfylg35w0syh58sm7gh53q5vvn7hd7c6nngyseftjxl",
            "age16ldycczfl4ne520ar8kx56t00u55s8gq69dy0q72hh77jl3qgu7ql9a8wc"
          ]
        }
      ],
      "path_regex": "hosts/common/secrets.yaml$"
    }
  ]
}
