#!/usr/bin/env bash

exec 2>>~/.cache/bspwm/stderr

echo 'Launched bspwm' >&2

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom  --xrender-sync-fence --experimental-backends --backend glx \
    --use-damage --vsync --config /dev/null --show-all-xerrors \
    --glx-no-stencil --log-level INFO --log-file ~/.cache/picom.out &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
