#!/usr/bin/env bash

class="$2"

echo "$@" >~/f

# Android Emulator has an empty window class. I have no clue why.
if [[ "$class" == *.exe ]] || [[ "$class" == "" ]]; then
    echo "state=floating"
fi
